CREATE TABLE [dbo].[ROLES]
(
[idRol] [int] NOT NULL,
[Nombre] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[Descripcion] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ROLES] ADD CONSTRAINT [PK__ROLES__3C872F760BAF61F0] PRIMARY KEY CLUSTERED  ([idRol]) ON [PRIMARY]
GO
