CREATE TABLE [dbo].[PROVINCIA]
(
[idProvincia] [int] NOT NULL,
[Nombre] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROVINCIA] ADD CONSTRAINT [PK__PROVINCI__5F9F113C6CED1515] PRIMARY KEY CLUSTERED  ([idProvincia]) ON [PRIMARY]
GO
