CREATE TABLE [dbo].[RECETAS]
(
[idReceta] [int] NOT NULL,
[idDoctor] [int] NULL,
[idCliente] [int] NULL,
[Imagen] [image] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[RECETAS] ADD CONSTRAINT [PK__RECETAS__7D03FC81D01DFD09] PRIMARY KEY CLUSTERED  ([idReceta]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RECETAS] ADD CONSTRAINT [FK__RECETAS__idClien__571DF1D5] FOREIGN KEY ([idCliente]) REFERENCES [dbo].[CLIENTE] ([Cedula])
GO
ALTER TABLE [dbo].[RECETAS] ADD CONSTRAINT [FK__RECETAS__idDocto__5629CD9C] FOREIGN KEY ([idDoctor]) REFERENCES [dbo].[DOCTORES] ([Cedula])
GO
