CREATE TABLE [dbo].[RECETAS]
(
[idReceta] [int] NOT NULL,
[idDoctor] [int] NULL,
[idCliente] [int] NULL,
[Imagen] [image] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[RECETAS] ADD CONSTRAINT [PK__RECETAS__7D03FC81592E0C6A] PRIMARY KEY CLUSTERED  ([idReceta]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RECETAS] ADD CONSTRAINT [FK__RECETAS__idClien__5AEE82B9] FOREIGN KEY ([idCliente]) REFERENCES [dbo].[CLIENTE] ([Cedula])
GO
ALTER TABLE [dbo].[RECETAS] ADD CONSTRAINT [FK__RECETAS__idDocto__59FA5E80] FOREIGN KEY ([idDoctor]) REFERENCES [dbo].[DOCTORES] ([Cedula])
GO
