CREATE TABLE [dbo].[PRODUCTOXSUCURSAL]
(
[idSucursal] [int] NOT NULL,
[codProducto] [int] NOT NULL,
[Cantidad] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTOXSUCURSAL] ADD CONSTRAINT [PK__PRODUCTO__2299EE9BE19A8A0E] PRIMARY KEY CLUSTERED  ([idSucursal], [codProducto]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTOXSUCURSAL] ADD CONSTRAINT [FK__PRODUCTOX__codPr__4CA06362] FOREIGN KEY ([codProducto]) REFERENCES [dbo].[PRODUCTOS] ([idProducto])
GO
ALTER TABLE [dbo].[PRODUCTOXSUCURSAL] ADD CONSTRAINT [FK__PRODUCTOX__idSuc__4BAC3F29] FOREIGN KEY ([idSucursal]) REFERENCES [dbo].[SUCURSAL] ([idSucursal])
GO
