CREATE TABLE [dbo].[DETALLEPEDIDO]
(
[idProducto] [int] NOT NULL,
[idPedido] [int] NOT NULL,
[Cantidad] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLEPEDIDO] ADD CONSTRAINT [PK__DETALLEP__6D6BC0A92EDBC9A9] PRIMARY KEY CLUSTERED  ([idProducto], [idPedido]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLEPEDIDO] ADD CONSTRAINT [FK__DETALLEPE__idPed__4E88ABD4] FOREIGN KEY ([idPedido]) REFERENCES [dbo].[PEDIDOS] ([idPedido])
GO
ALTER TABLE [dbo].[DETALLEPEDIDO] ADD CONSTRAINT [FK__DETALLEPE__idPed__5070F446] FOREIGN KEY ([idPedido]) REFERENCES [dbo].[PEDIDOS] ([idPedido])
GO
ALTER TABLE [dbo].[DETALLEPEDIDO] ADD CONSTRAINT [FK__DETALLEPE__idPro__4D94879B] FOREIGN KEY ([idProducto]) REFERENCES [dbo].[PRODUCTOS] ([idProducto])
GO
