CREATE TABLE [dbo].[PEDIDOS]
(
[idPedido] [int] NOT NULL,
[sucursalRecojo] [int] NULL,
[idCliente] [int] NULL,
[horaRecojo] [time] NULL,
[Telefono] [int] NULL,
[Imagen] [image] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIDOS] ADD CONSTRAINT [PK__PEDIDOS__A9F619B744391591] PRIMARY KEY CLUSTERED  ([idPedido]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIDOS] ADD CONSTRAINT [FK__PEDIDOS__idClien__52593CB8] FOREIGN KEY ([idCliente]) REFERENCES [dbo].[CLIENTE] ([Cedula])
GO
ALTER TABLE [dbo].[PEDIDOS] ADD CONSTRAINT [FK__PEDIDOS__sucursa__5165187F] FOREIGN KEY ([sucursalRecojo]) REFERENCES [dbo].[SUCURSAL] ([idSucursal])
GO
