CREATE TABLE [dbo].[EMPLEADOXSUCURSAL]
(
[idSucursal] [int] NOT NULL,
[idEmpleado] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPLEADOXSUCURSAL] ADD CONSTRAINT [PK__EMPLEADO__222E3BDBDA8FFE7F] PRIMARY KEY CLUSTERED  ([idSucursal], [idEmpleado]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPLEADOXSUCURSAL] ADD CONSTRAINT [FK__EMPLEADOX__idEmp__48CFD27E] FOREIGN KEY ([idEmpleado]) REFERENCES [dbo].[EMPLEADO] ([idEmpleado])
GO
ALTER TABLE [dbo].[EMPLEADOXSUCURSAL] ADD CONSTRAINT [FK__EMPLEADOX__idSuc__47DBAE45] FOREIGN KEY ([idSucursal]) REFERENCES [dbo].[SUCURSAL] ([idSucursal])
GO
