CREATE TABLE [dbo].[DISTRITO]
(
[idDistrito] [int] NOT NULL,
[idCanton] [int] NULL,
[Nombre] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DISTRITO] ADD CONSTRAINT [PK__DISTRITO__494092A8CC8177A6] PRIMARY KEY CLUSTERED  ([idDistrito]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DISTRITO] ADD CONSTRAINT [FK__DISTRITO__idCant__5EBF139D] FOREIGN KEY ([idCanton]) REFERENCES [dbo].[CANTON] ([idCanton])
GO
