CREATE TABLE [dbo].[PADECIMIENTOS]
(
[idPadecimiento] [int] NOT NULL,
[idUsuario] [int] NULL,
[Fecha] [date] NULL,
[Nombre] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL,
[Descripcion] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PADECIMIENTOS] ADD CONSTRAINT [PK__PADECIMI__D21C34312A8785DE] PRIMARY KEY CLUSTERED  ([idPadecimiento]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PADECIMIENTOS] ADD CONSTRAINT [FK__PADECIMIE__idUsu__52593CB8] FOREIGN KEY ([idUsuario]) REFERENCES [dbo].[CLIENTE] ([Cedula])
GO
