CREATE TABLE [dbo].[ROLESXEMPLEADO]
(
[idUsuario] [int] NOT NULL,
[idRol] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ROLESXEMPLEADO] ADD CONSTRAINT [PK__ROLESXEM__179F5151D2B55D8F] PRIMARY KEY CLUSTERED  ([idUsuario], [idRol]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ROLESXEMPLEADO] ADD CONSTRAINT [FK__ROLESXEMP__idUsu__49C3F6B7] FOREIGN KEY ([idUsuario]) REFERENCES [dbo].[EMPLEADO] ([idEmpleado])
GO
ALTER TABLE [dbo].[ROLESXEMPLEADO] ADD CONSTRAINT [FK__ROLESXEMP__idRol__4AB81AF0] FOREIGN KEY ([idRol]) REFERENCES [dbo].[ROLES] ([idRol])
GO
