CREATE TABLE [dbo].[DETALLERECETA]
(
[idMedicamento] [int] NOT NULL,
[idReceta] [int] NOT NULL,
[Cantidad] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLERECETA] ADD CONSTRAINT [PK__DETALLER__4562739077C3735C] PRIMARY KEY CLUSTERED  ([idMedicamento], [idReceta]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLERECETA] ADD CONSTRAINT [FK__DETALLERE__idMed__4CA06362] FOREIGN KEY ([idMedicamento]) REFERENCES [dbo].[PRODUCTOS] ([idProducto])
GO
